### ISSUE TITLE
LGPLv3 is probably not a suitable license for a dataset.

### ISSUE THREAD

**Issue by lasconic** [Audiveris/omr-dataset-tools#1]
See https://opendatacommons.org/guide/

**Comment by maximumspatium** [comment]
I find the repository name `omr-dataset` misleading because it isn't going to store actual datasets but merely software tools for producing training data. This purpose becomes obvious to me after reading the supplied wiki.

I propose to rename this repository to reflect its true purpose. After that, we can negotiate a proper license for it.

**Comment by hbitteur** [comment]
Rename repository as `omr-dataset-generation` or even a more general `omr-dataset-tools`?
Training is the most immediate goal, but other uses may appear.

**Comment by lasconic** [comment]
`omr-dataset-tools`  👍

**Comment by maximumspatium** [comment]
+1 for `omr-dataset-tools`

**Comment by hbitteur** [comment]
Regarding license for the **data** itself, and based on Nicolas info, I would vote for the "share-alike" [Open Database License](https://opendatacommons.org/licenses/odbl/summary/)

Regarding license for the software **tools** to produce the data, I would vote for AGPL (like Audiveris V5).

**Comment by lasconic** [comment]
Hangout April 28. 
* We agree on ODBL license for the data.
* For the license of the tools, we agree on AGPLv3
* MuseScore keeps its license. The branch is here: https://github.com/musescore/MuseScore/tree/imeta

**Comment by hbitteur** [comment]
Tools license has been set to AGPLv3.
Data license will be set to ODBL when we have data.
